package com.bank.model;

public enum Acao {
    CADASTRAR_USUARIO,
    CADASTRAR_CONTA,
    LISTAR_CONTAS,
    CONSULTAR_SALDO,
    DEPOSITAR,
    SACAR,
    TRANSFERIR,
    AUTENTICAR_USUARIO,
    LOGOUT,
    SAIR,
    DADOS_TESTE,
    IMPRIMIR_RELATORIO
}
